project:
  type: website

website:
  title: "VAA-Project8"
  navbar:
    left:
      - text: Introduction
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Shiny App
        href: x
      - text: Poster
        href: x

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

