---
title: "Insights into Government Procurement"
---

Welcome to our project website for ISSS608 Visual Analytics & Applications where we will be deriving insights into government procurement.

Government Electronic Business (GeBIZ) is the Singapore Government\'s one-stop e-procurement portal for use by all ministries and agencies in tendering for goods and services. It encompasses all the public sector\'s request for proposals, quotations, and tenders which suppliers can easily search for and download relevant information packages, and thereafter submit their bids electronically.  

There is a huge amount of data collected on past procurements since GeBIZ\'s launch in 2000 which in turn becomes a valuable source to generate powerful insights into government procurements. This treasure trove has not been widely explored or utilized (at least publicly) and through a R Shiny application, we seek to explore meaningful insights that can aide anyone looking into government procurements, be it the government agencies themselves, the suppliers keen on participating in government tenders, or even a member of the general public with an interest to see one facet of how tax dollars are spent.

Group 8: Eda Chang \| Wang Kunrui (Olivia) \| Willie Lau
